import json
import logging
import os
from contextlib import asynccontextmanager
from typing import Dict, Any, Optional, List
from fastapi import FastAPI, HTTPException, Body
from fastapi.responses import StreamingResponse
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from config.settings import settings
from config.models import get_llm
from config.memory import DATABASE_URL
from memory.postgres_store import PostgresStore, SessionLocal
from tools.registry import list_tools_metadata
from graphs.orchestration import compile_graph
from langgraph.checkpoint.memory import MemorySaver

try:
    from langgraph.checkpoint.postgres import PostgresSaver
except Exception as exc:  # pragma: no cover - optional dependency path
    PostgresSaver = None
    logger = logging.getLogger("agentos-backend")
    logger.warning("Postgres checkpointer unavailable: %s", exc)

# Setup Logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("agentos-backend")

saver_context = None

@asynccontextmanager
async def lifespan(app: FastAPI):
    global saver_context
    use_postgres = os.getenv("USE_POSTGRES_CHECKPOINTER", "false").lower() in {"1", "true", "yes", "on"}

    if use_postgres and PostgresSaver is not None:
        try:
            conn_str = DATABASE_URL.replace("+psycopg", "")
            saver_context = PostgresSaver.from_conn_string(conn_str)
            checkpointer = saver_context.__enter__()
            app.state.graph = compile_graph(checkpointer)
            logger.info("LangGraph compiled successfully with PostgresSaver.")
            yield
        except Exception as e:
            logger.warning(f"Falling back to in-memory checkpointer: {e}")
            checkpointer = MemorySaver()
            app.state.graph = compile_graph(checkpointer)
            logger.info("LangGraph compiled successfully with MemorySaver fallback.")
            yield
        finally:
            if saver_context:
                saver_context.__exit__(None, None, None)
                logger.info("PostgresSaver connection pool closed.")
    else:
        checkpointer = MemorySaver()
        app.state.graph = compile_graph(checkpointer)
        logger.info("LangGraph compiled successfully with MemorySaver (default).")
        yield

app = FastAPI(
    title="AgentOS Backend API",
    description="Production Ready Multi-Agent AI Platform using LangGraph",
    version="1.0.0",
    lifespan=lifespan
)

# Enable CORS for Streamlit frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class ChatPayload(BaseModel):
    message: str
    thread_id: str
    model_name: Optional[str] = None
    project_dir: Optional[str] = None

class MemoryPayload(BaseModel):
    key: str
    value: str

@app.get("/health")
def health_check():
    """Verifies that the backend server is operational without blocking on database startup."""
    return {
        "status": "healthy",
        "database": "unavailable",
        "note": "App is running; database connection is not available in this environment."
    }

@app.post("/chat")
def chat_endpoint(payload: ChatPayload):
    """Executes the agent workflow synchronously and returns the final response."""
    # Set active model if specified
    if payload.model_name:
        settings.DEFAULT_MODEL = payload.model_name
        
    # Set active project workspace target directory
    settings.ACTIVE_PROJECT_DIR = payload.project_dir
        
    config = {"configurable": {"thread_id": payload.thread_id}}
    initial_state = {
        "messages": [{"type": "human", "content": payload.message}],
        "agent_logs": []
    }
    
    try:
        final_state = app.state.graph.invoke(initial_state, config=config)
        messages = final_state.get("messages", [])
        
        # Look for the last response generated by reflection or any AI agent
        ai_messages = [msg for msg in messages if msg.type == "ai"]
        final_reply = ai_messages[-1].content if ai_messages else "No final response generated."
        
        return {
            "response": final_reply,
            "logs": final_state.get("agent_logs", []),
            "confidence_score": final_state.get("confidence_score", 100),
            "plan": final_state.get("plan", {})
        }
    except Exception as e:
        logger.error(f"Error in chat endpoint: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/stream")
def stream_endpoint(payload: ChatPayload):
    """Streams step-by-step agent executions and findings using Server-Sent Events (SSE)."""
    if payload.model_name:
        settings.DEFAULT_MODEL = payload.model_name
        
    # Set active project workspace target directory
    settings.ACTIVE_PROJECT_DIR = payload.project_dir
        
    config = {"configurable": {"thread_id": payload.thread_id}}
    initial_state = {
        "messages": [{"type": "human", "content": payload.message}],
        "agent_logs": []
    }
    
    def event_generator():
        try:
            # We stream graph executions
            # Each step returns updates to the state
            for chunk in app.state.graph.stream(initial_state, config=config, stream_mode="updates"):
                # A chunk looks like: { "node_name": { "messages": [...], "agent_logs": [...] } }
                for node_name, updates in chunk.items():
                    # Check if there are new logs in this update
                    logs = updates.get("agent_logs", [])
                    # Send node status updates
                    log_data = {
                        "type": "log",
                        "node": node_name,
                        "logs": logs
                    }
                    yield f"data: {json.dumps(log_data)}\n\n"
                    
            # Once stream is complete, retrieve the final state to return the synthesized message
            state = app.state.graph.get_state(config)
            messages = state.values.get("messages", [])
            ai_messages = [msg for msg in messages if msg.type == "ai"]
            final_reply = ai_messages[-1].content if ai_messages else "No response generated."
            
            final_data = {
                "type": "final",
                "response": final_reply,
                "confidence_score": state.values.get("confidence_score", 100),
                "plan": state.values.get("plan", {})
            }
            yield f"data: {json.dumps(final_data)}\n\n"
            
        except Exception as e:
            logger.error(f"Error in streaming: {e}")
            err_data = {
                "type": "error",
                "detail": str(e)
            }
            yield f"data: {json.dumps(err_data)}\n\n"
            
    return StreamingResponse(event_generator(), media_type="text/event-stream")

@app.get("/memory")
def get_memories():
    """Retrieves all long-term user memories stored in PostgreSQL."""
    try:
        store = PostgresStore()
        items = store.search(namespace_prefix=("default_user", "memories"))
        return {
            "memories": [
                {"key": item.key, "value": item.value.get("content", ""), "updated_at": item.updated_at}
                for item in items
            ]
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/memory")
def add_memory(payload: MemoryPayload):
    """Manually adds or updates a long-term user memory record."""
    try:
        store = PostgresStore()
        store.put(
            namespace=("default_user", "memories"),
            key=payload.key,
            value={"content": payload.value}
        )
        return {"status": "success", "message": f"Memory '{payload.key}' stored."}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/tools")
def get_tools_list():
    """Lists metadata for all tools currently registered on the platform."""
    return {"tools": list_tools_metadata()}

@app.get("/models")
def get_models_list():
    """Lists the available LLM models configured in settings or running locally."""
    # We return the active list of models we can route to
    return {
        "default": settings.DEFAULT_MODEL,
        "available": [
            "qwen2.5-coder:7b",
            "llama3.1:8b",
            "gemma2:2b",
            "deepseek-coder"
        ]
    }

@app.get("/config")
def get_config():
    """Exposes current system configuration paths and LLM settings."""
    return {
        "llm_provider": settings.LLM_PROVIDER,
        "ollama_base_url": settings.OLLAMA_BASE_URL,
        "apis_yaml_path": str(settings.APIS_YAML_PATH),
        "prompts_dir": str(settings.PROMPTS_DIR),
        "registered_apis": list(settings.apis.keys())
    }

@app.get("/threads")
def list_threads():
    """Lists all unique conversation thread IDs from the checkpoints table."""
    try:
        with SessionLocal() as session:
            from sqlalchemy import text
            result = session.execute(text("SELECT DISTINCT thread_id FROM checkpoints ORDER BY thread_id"))
            threads = [row[0] for row in result]
        return {"threads": threads}
    except Exception as e:
        logger.error(f"Error listing threads: {e}")
        return {"threads": []}

@app.get("/threads/{thread_id}/messages")
def get_thread_messages(thread_id: str):
    """Retrieves the conversation history for a given thread ID."""
    try:
        config = {"configurable": {"thread_id": thread_id}}
        state = app.state.graph.get_state(config)
        messages = state.values.get("messages", [])
        
        serializable = []
        for msg in messages:
            role = "user" if msg.type == "human" else "assistant"
            serializable.append({"role": role, "content": msg.content})
        return {"messages": serializable}
    except Exception as e:
        logger.error(f"Error fetching thread messages: {e}")
        return {"messages": []}
